/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author chiki
 */
public class Longitud extends javax.swing.JFrame {

    /**
     * Creates new form Conversiones
     */
    public Longitud() {
        initComponents();
        setLocationRelativeTo(this);
        
        menu.addItem("");
        menu.addItem("m");
        menu.addItem("km");
        menu.addItem("mm");
        menu.addItem("cm");
        menu.addItem("mi");
        menu.addItem("yd");
        menu.addItem("ft");
        menu.addItem("in");
        menu.addItem("nm");
        
        r1.setEditable(false);
        r2.setEditable(false);
        r3.setEditable(false);
        r4.setEditable(false);
        r5.setEditable(false);
        r6.setEditable(false);
        r7.setEditable(false);
        r8.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        L = new javax.swing.JLabel();
        V = new javax.swing.JLabel();
        M = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombre = new javax.swing.JLabel();
        menu = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        u1 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        u2 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        u3 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        r3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        u4 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        r4 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        u5 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        r5 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        u6 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        r6 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        a7 = new javax.swing.JLabel();
        u7 = new javax.swing.JLabel();
        r7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        u8 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        r8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        L.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        L.setForeground(new java.awt.Color(0, 204, 51));
        L.setText("LONGITUD");
        L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LMouseClicked(evt);
            }
        });

        V.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        V.setForeground(new java.awt.Color(102, 102, 102));
        V.setText("VOLUMEN");
        V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VMouseClicked(evt);
            }
        });

        M.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        M.setForeground(new java.awt.Color(102, 102, 102));
        M.setText("MASA");
        M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMouseClicked(evt);
            }
        });

        A.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        A.setForeground(new java.awt.Color(102, 102, 102));
        A.setText("ÁREA");
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });

        T.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        T.setForeground(new java.awt.Color(102, 102, 102));
        T.setText("TEMPERATURA");
        T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TMouseClicked(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        nombre.setText("Nombre");

        menu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                menuItemStateChanged(evt);
            }
        });

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("Cantidad");

        u1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u1.setText("Unidad");

        a1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a1.setText("abrev.");

        u2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u2.setText("Unidad");

        a2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a2.setText("abrev.");

        u3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u3.setText("Unidad");

        a3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a3.setText("abrev.");

        u4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u4.setText("Unidad");

        a4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a4.setText("abrev.");

        u5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u5.setText("Unidad");

        a5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a5.setText("abrev.");

        u6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u6.setText("Unidad");

        a6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a6.setText("abrev.");

        a7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a7.setText("abrev.");

        u7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u7.setText("Unidad");

        jButton1.setText("BORRAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        u8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        u8.setText("Unidad");

        a8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        a8.setText("abrev.");

        jButton2.setText("SALIR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator8)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(u1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator7)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jSeparator9)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(u6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(u7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addComponent(jSeparator12)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(L)
                        .addGap(18, 18, 18)
                        .addComponent(A)
                        .addGap(18, 18, 18)
                        .addComponent(M)
                        .addGap(18, 18, 18)
                        .addComponent(V)
                        .addGap(18, 18, 18)
                        .addComponent(T))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(u8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(15, 15, 15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(a8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(V, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(u1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u2)
                                .addGap(5, 5, 5)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(u7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(u8)
                            .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TMouseClicked
        // TODO add your handling code here:
        
        Temperatura t = new Temperatura();
        t.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_TMouseClicked

    private void LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LMouseClicked

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        // TODO add your handling code here:
        
        Area a = new Area();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_AMouseClicked

    private void MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseClicked
        // TODO add your handling code here:
        
        Masa m = new Masa();
        m.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_MMouseClicked

    private void VMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VMouseClicked
        // TODO add your handling code here:
        
        Volumen v = new Volumen();
        v.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_VMouseClicked

    private void menuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_menuItemStateChanged
        // TODO add your handling code here:
        
        String unidad = (String) menu.getSelectedItem();
        
        if(unidad.equals("m")){
            nombre.setText("Metro");
            u1.setText("Kilómetro");
            a1.setText("km");
            u2.setText("Milimetro");
            a2.setText("mm");
            u3.setText("Centímetro");
            a3.setText("cm");
            u4.setText("Milla");
            a4.setText("mi");
            u5.setText("Yarda");
            a5.setText("yd");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("km")){
            nombre.setText("Kilómetro");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Milimetro");
            a2.setText("mm");
            u3.setText("Centímetro");
            a3.setText("cm");
            u4.setText("Milla");
            a4.setText("mi");
            u5.setText("Yarda");
            a5.setText("yd");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("mm")){
            nombre.setText("Milímetro");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Centímetro");
            a3.setText("cm");
            u4.setText("Milla");
            a4.setText("mi");
            u5.setText("Yarda");
            a5.setText("yd");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("cm")){
            nombre.setText("Centímetro");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Milla");
            a4.setText("mi");
            u5.setText("Yarda");
            a5.setText("yd");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("mi")){
            nombre.setText("Milimetro");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Centímetro");
            a4.setText("cm");
            u5.setText("Yarda");
            a5.setText("yd");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("yd")){
            nombre.setText("Yarda");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Centímetro");
            a4.setText("cm");
            u5.setText("Milla");
            a5.setText("mi");
            u6.setText("Pie");
            a6.setText("ft");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("ft")){
            nombre.setText("Pie");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Centímetro");
            a4.setText("cm");
            u5.setText("Milla");
            a5.setText("mi");
            u6.setText("Yarda");
            a6.setText("yd");
            u7.setText("Pulgada");
            a7.setText("in");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("in")){
            nombre.setText("Pulgada");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Centímetro");
            a4.setText("cm");
            u5.setText("Milla");
            a5.setText("mi");
            u6.setText("Yarda");
            a6.setText("yd");
            u7.setText("Pie");
            a7.setText("ft");
            u8.setText("Nanómetro");
            a8.setText("nm");
        }
        
        if(unidad.equals("nm")){
            nombre.setText("Nanómetro");
            u1.setText("Metro");
            a1.setText("m");
            u2.setText("Kilómetro");
            a2.setText("km");
            u3.setText("Milímetro");
            a3.setText("mm");
            u4.setText("Centímetro");
            a4.setText("cm");
            u5.setText("Milla");
            a5.setText("mi");
            u6.setText("Yarda");
            a6.setText("yd");
            u7.setText("Pie");
            a7.setText("ft");
            u8.setText("Pulgada");
            a8.setText("in");
            
        }
        
    }//GEN-LAST:event_menuItemStateChanged

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        // TODO add your handling code here:
        
        float cant, res1, res2, res3, res4, res5, res6, res7, res8;
        
        cant=Float.parseFloat(cantidad.getText());
        
        String unidad = (String) menu.getSelectedItem();
        
        //Metro
        if(unidad.equals("m")){
            //m a km
            res1=(float) cant/1000;
            r1.setText("" + res1);
            
            //m a mm
            res2=(float) cant*1000;
            r2.setText("" + res2);
            
            //m a cm
            res3=(float) cant*100;
            r3.setText("" + res3);
            
            //m a mi
            if(cant>1){
            res4=(float) (cant/1609);
            r4.setText("" + res4);
            }
            else{
            r4.setText("" + "0.000621");
            }
            
            //m a yd
            res5=(float) (cant*1.094);
            r5.setText("" + res5);
            
            //m a ft
            res6=(float) (cant*3.281);
            r6.setText("" + res6);
            
            //m a in
            res7=(float) (cant*39.37);
            r7.setText("" + res7);
            
            //m a nm
            res7=(int) (cant*1);
            r8.setText("" + cant + "e+9");
        }
        
        //Kilometro
        if(unidad.equals("km")){
            //km a m
            res1=(float) (cant*1000);
            r1.setText("" + res1);
            
            //km a mm
            res2=(float) (cant*1000000);
            r2.setText("" + res2);
            
            //km a cm
            res3=(float) (cant*100000);
            r3.setText("" + res1);
            
            //km a mi
            res4=(float) (cant*0.621);
            r4.setText("" + res2);
            
            //km a yd
            res5=(float) (cant*1094);
            r5.setText("" + res1);
            
            //km a ft
            res6=(float) (cant*3281);
            r6.setText("" + res2);
            
            //km a in
            res7=(float) (cant*39370);
            r7.setText("" + res1);
            
            //km a nm
            r8.setText("" + cant + "e+12");
        }
        
        //Milimetro 
        if(unidad.equals("mm")){
            //mm a m
            res1=(float) (cant/1000);
            r1.setText("" + res1);
            
            //mm a km
            res2=(float) (cant/1000000);
            r2.setText("" + res2);
            
            //mm a cm
            res3=(float) (cant/10);
            r3.setText("" + res3);
            
            //mm a mi
            res4=(float) (cant/1.609000000);
            r4.setText("" + res4);
            
            //mm a yd
            res5=(float) (cant/914);
            r5.setText("" + res5);
            
            //mm a ft
            res6=(float) (cant/305);
            r6.setText("" + res6);
            
            //mm a in 
            res7=(float) (cant/25.4);
            r7.setText("" + res7);
            
            //mm a nm 
            
            res8=(float) (cant*1000000);
            r8.setText("" + res8);
        }
        
        //Centimetro
        if(unidad.equals("cm")){
            //cm a m
            res1=(float) (cant/100);
            r1.setText("" + res1);
            
            //cm a km 
            res2=(float) (cant/100000);
            r2.setText("" + res2);
            
            //cm a mm 
            res3=(float) (cant*10);
            r3.setText("" + res3);
            
            //cm a mi
            res4=(float) (cant/160934);
            r4.setText("" + res4);
            
            //cm a yd
            res5=(float) (cant/91.44);
            r5.setText("" + res5);
            
            //cm a ft 
            res6=(float) (cant/30.48);
            r6.setText("" + res6);
            
            //cm a in 
            res7=(float) (cant/2.54);
            r7.setText("" + res7);
            
            //cm a nm
            res8=(float) (cant*10000000);
            r8.setText("" + res8);            
        }
        
        //Milla 
        if(unidad.equals("mi")){
            //mi a m 
            res1=(float) (cant*1609);
            r1.setText("" + res1);
            
            //mi a km
            res2=(float) (cant*1.609);
            r2.setText("" + res2);
            
            //mi a mm
            res3=(float) (cant*1.609000000);
            r3.setText("" + res3);
            
            //mi a cm 
            res4=(float) (cant*160934);
            r4.setText("" + res4);
            
            //mi a yd
            res5=(float) (cant*1760);
            r5.setText("" + res5);
            
            //mi a ft
            res6=(float) (cant*5280);
            r6.setText("" + res6);
            
            //mi a in 
            res7=(float) (cant*63360);
            r7.setText("" + res7);

            //mi a nm
            res8=(float) (cant*1.609000000000000);
            r8.setText("" + res8 + "e+12");
        }
        
        //Yarda 
        if(unidad.equals("yd")){
            //yd a m
            res1=(float) (cant/1.094);
            r1.setText("" + res1);
            
            //yd a km
            res2=(float) (cant/1094);
            r2.setText("" + res2);
            
            //yd a mm
            res3=(float) (cant*914);
            r3.setText("" + res3);
            
            //yd a cm 
            res4=(float) (cant*91.44);
            r4.setText("" + res4);
            
            //yd a mi
            res5=(float) (cant/1760);
            r5.setText("" + res5);
            
            //yd a ft
            res6=(float) (cant*3);
            r6.setText("" + res6);
            
            //yd a in
            res7=(float) (cant*36);
            r7.setText("" + res7);
            
            //yd a nm
            res8=(float) (cant*9.14400000000);
            r8.setText("" + res8);
        }
        
        //Pie
        if (unidad.equals("ft")){
            //ft a m
            res1=(float) (cant/3.281);
            r1.setText("" + res1);
            
            //ft a km
            res2=(float) (cant/3281);
            r2.setText("" + res2);
            
            //ft a mm
            res3=(float) (cant*305);
            r3.setText("" + res3);
            
            //ft a cm
            res4=(float) (cant*30.48);
            r4.setText("" + res4);
            
            //ft a mi
            res5=(float) (cant/5280);
            r5.setText("" + res5);
            
            //ft a yd
            res6=(float) (cant/3);
            r6.setText("" + res6);
            
            //ft a in
            res7=(float) (cant*12);
            r7.setText("" + res7);
            
            //ft a nm
            res8=(float) (cant*3.04800000000);
            r8.setText("" + res8);
        }
        
        //Pulgada 
        if (unidad.equals("in")){
            //in a m
            res1=(float) (cant/39.37);
            r1.setText("" + res1);
           
            //in a km
            res2=(float) (cant/39370);
            r2.setText("" + res2);
            
            //in a mm
            res3=(float) (cant*25.4);
            r3.setText("" + res3);
            
            //in a cm
            res4=(float) (cant*2.54);
            r4.setText("" + res4);
            
            //in a mi
            res5=(float) (cant/63360);
            r5.setText("" + res5);
            
            //in a yd
            res6=(float) (cant/36);
            r6.setText("" + res6);
            
            //in a ft
            res7=(float) (cant/12);
            r7.setText("" + res7);
            
            //in a nm
            res7=(float) (cant*2.540000000);
            r7.setText("" + res7);
        }
        
        //Nanometro
        if(unidad.equals("nm")){
            //nm a m
            res1=(float) (cant/1000000000);
            r1.setText("" + res1);
            
            //nm a km
            r2.setText("" + cant + "e+12");
            
            //nm a mm
            res3=(float) (cant/1000000);
            r3.setText("" + res3);
            
            //nm a cm
            res4=(float) (cant/10000000);
            r4.setText("" + res4);
            
            //nm a mi
            res5=(float) (cant/1.609000000000000);
            r5.setText("" + res5);
            
            //nm a yd
            res6=(float) (cant/9.14400000000);
            r6.setText("" + res6);
            
            //nm a ft
            res7=(float) (cant/3.04800000000);
            r7.setText("" + res7);
            
            //nmm a in
            res8=(float) (cant/2.540000000);
            r8.setText("" + res8);
        }
        
    }//GEN-LAST:event_cantidadKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        cantidad.setText("");
        r1.setText("");
        r2.setText("");
        r3.setText("");
        r4.setText("");
        r5.setText("");
        r6.setText("");
        r7.setText("");
        r8.setText("");
        menu.setSelectedIndex(0);
        
        nombre.setText("Nombre");
        u1.setText("Unidad");
        a1.setText("Abrev.");
        u2.setText("Unidad");
        a2.setText("Abrev.");
        u3.setText("Unidad");
        a3.setText("Abrev.");
        u4.setText("Unidad");
        a4.setText("Abrev.");
        u5.setText("Unidad");
        a5.setText("Abrev.");
        u6.setText("Unidad");
        a6.setText("Abrev.");
        u7.setText("Unidad");
        a7.setText("Abrev.");
        u8.setText("Unidad");
        a8.setText("Abrev.");
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Longitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Longitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel L;
    private javax.swing.JLabel M;
    private javax.swing.JLabel T;
    private javax.swing.JLabel V;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> menu;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JTextField r8;
    private javax.swing.JLabel u1;
    private javax.swing.JLabel u2;
    private javax.swing.JLabel u3;
    private javax.swing.JLabel u4;
    private javax.swing.JLabel u5;
    private javax.swing.JLabel u6;
    private javax.swing.JLabel u7;
    private javax.swing.JLabel u8;
    // End of variables declaration//GEN-END:variables
}
